### ISSUE TITLE
Add Facebook open graph meta tags

### ISSUE THREAD

**Issue by andri** [piratar/wasa2il#10]
Add relevant open graph tags to public pages of the system so that shared links on Facebook get more attention. I can upload a photo you guys can use for this. 

https://www.facebook.com/groups/153461471471460/permalink/509258895891714/

**Comment by andri** [comment]
T.d svona:

<meta property="og:type" content="website" />
<meta property="og:title" content="Titill máls" />
<meta property="og:description" content="Útdráttur" />
<meta property="og:url" content="http://x.piratar.is/full/url" />
<meta property="og:site_name" content="Wasa2il - Píratar" />
<meta property="og:image" content="http://x.piratar.is/img/fb.png" />

**Comment by andri** [comment]
Mynd!
![image](https://cloud.githubusercontent.com/assets/123914/9429954/b15218a0-49d1-11e5-8945-28b29dc51bf5.png)

**Comment by stjanigunnars** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Facebook open graph meta tags](https://trello.com/c/fj9sjyxC/9-add-facebook-open-graph-meta-tags)

**Comment by helgihg** [comment]
Done.
