### ISSUE TITLE
Access controls on Issue votes don't work?

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#101]
It appears that anyone can currently vote on an issue, whether they are a member of the polity or not.

At this point I don't know whether this is a UI bug or an actual access bug. Investigating.

**Comment by bjornlevi** [comment]
When the votes are counted they are filtered based on who has a right to
vote (should be)

But yes, this is a very reverse way of getting to the point.

**Comment by BjarniRunar** [comment]
OK. so this is a duplicate of #84 then, apparently this applies both to issues and elections.
