### ISSUE TITLE
Abstaining is an action not inaction

### ISSUE THREAD

**Issue by BergthorTh** [piratar/wasa2il#102]
As it is now when an issue is in the voting phase the default vote for a user is "abstain" no matter whether that user even logs on during voting or not. Abstaining is an action and should be considered as such when voting on issues. The default state for a user who has not voted should be "has not voted". The user should then be able to choose "yes", "no" or "abstain".

**Comment by bjornlevi** [comment]
And how are you going to count that towards a majority?

Say 10 say yes, 10 abstain and 5 say no? Is that a majority or not?

**Comment by helgihg** [comment]
Abstentions should be simply ignored. They're not counted towards the
result, but rather used as an indicator of how many people didn't want
to vote either way for one reason or another, but still "showed up" to vote.

**Comment by bjornlevi** [comment]
"Should" ... of course. Democratic results belong to those that participate.

So why add this feature if it is going to be trashed anyway? What are we going to use the abstainee votes for? What kind of statistics? To what end?

Don't get me wrong. I like data for the sake of data. It's just necessary to have a goal to justify or compare to.

**Comment by helgihg** [comment]
Personally, I don't really care whether abstention is counted or not.

But I can imagine reasons:

* To measure actual participation. To show up and vote is participation
even if you don't feel comfortable voting either yes or no to a proposal.

* Those who abstain may want to express their will to do so. - To show
that they partook in the decision-making process.

* The statistics can be used to determine how united the polity is on an
issue. Could be useful if people disagree on how well something has been
discussed, for example. (Those who have made up their minds typically
always think plenty of discussion has taken place while those who
haven't disagree.)

**Comment by bjornlevi** [comment]
Yes, all possibilities. I'm just looking for reasons for the feature so it can be evaluated if it is doing it's job or not later on. 

So, according to the feature requester ( @BergthorTh ) - what is the goal?

(/qa hat off)

**Comment by bjornlevi** [comment]
Specifically I am wondering about the phrasing because "abstain" is a reference to formally decline to vote either for or against a proposal or motion. How it is translated would also matter because "kýs ekki" means something entirely different than "Leyfi öðrum að taka ákvörðun" - which then matters a lot for any kind of statistics collected and what can be deduced from those numbers.

**Comment by helgihg** [comment]
Imlemented in commit 7aacec3. The interface no longer assumes that the user is abstaining when first visiting the issue. Abstentions have actually been recorded for a while if the user presses the abstention button, and have recently been shown in the agreement list on the polity's front page, but the issue view has defaulted to showing abstention as an already made choice. Now all buttons remain unpressed until specifically pressed. Once a button has been pressed, the user cannot unpress, but must abstain if they don't wish to effect the vote.

This is also how Parliament in Iceland works (except there is a secret trick to remove abstentions, intended only to be used when MPs accidentally push another MP's button, and we don't need that).
