### ISSUE TITLE
Make the "My Profile" page more useful

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#107]
The "My Profile" page is currently optimized for users with a very large number of active documents and issues, and is not very helpful for new users or users who are primarily active as voters and commentors.

It would make sense to rethink this page a bit and make it into more of a landing page which highlights all the things a user might be interested in participating in - both issues/documents the user has commented or voted on, ongoing elections and other recent activity.

**Comment by BjarniRunar** [comment]
If done nicely, this page would make a good "front page" for logged in users. Or all users if the code is easily abstracted to do sensible things when not logged in.

**Comment by baldurjonsson** [comment]
Would it be sensible to keep the _profile_ view as is, as it is also used for users looking at other users, and make a new _myprofile_ view?

**Comment by BjarniRunar** [comment]
It makes sense to have a page that everyone else can look at, and you're right that that page should probably be different from the user's "home" page. The current profile page does neither task particularly well, IMO.

**Comment by viktorsmari** [comment]
I think the _/accounts/profile/username_ is good for looking at other users and see their non-private activity. Maybe others could see where that user commented recently and created documents etc?

We could then create a private "_my dashboard_" for users to see their own personal activity, example:

- Who commented on a document you created

- Someone mentioned you in a comment (if that were possible)

- Some election you took part in is about to end or has ended 

To help users have an overview of what they are involved in.

**Comment by baldurjonsson** [comment]
I'm testing out something of a _Dashboard_ or a _frontpage_.
Meanwhile I'm getting familiar with the system. :)

The idea is simple, when authenticated, both issues and elections up for vote are front and center on all your polities upon arrival.
When not authenticated you see the same for all polities whom are _public_.

Perhaps if you're not authenticated you should only see the _front_ polity

![image](https://cloud.githubusercontent.com/assets/3398226/17464649/86faceba-5cd3-11e6-824e-559a48721293.png)

**Comment by baldurjonsson** [comment]
@viktorsmari I don't know if it has been discussed before but your private dashboard idea could be part of a _cool_ notifcation feature

**Comment by helgihg** [comment]
@smari has made it more useful although it still does not function as a landing page as per the issue description. However, seeing that there are on-going major changes being implemented with the navigation and flow in general. The appropriate functionality for the profile page won't really be clear until that work is complete, especially considering that the landing-page mechanism described is likely to become a more central point of the web interface in general, regardless of user profiles.

Considering this, I'm closing this issue for now. May be re-opened later once the shifts in design and flow are closer to their inevitable awesomeness.
