### ISSUE TITLE
Make election times/dates easier to parse

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#114]
The current voting page shows the deadlines for candidacy and voting, but the words used are a bit unhelpful.

It would probably be better to say "Voting starts at XXX" and "candidates must announce before this deadline" in small print.

Similarly, once voting has begun it would make sense to use human language and big letters. Maybe even a javascript countdown?

**Comment by helgihg** [comment]
Fixed in commit bb06d1a. Note that the Icelandic translation is in a different commit coming right after. Also fixed the same issue in issues. Didn't do the big counter thing, because I feel that's a separate issue.
