### ISSUE TITLE
User can create usernames with ó

### ISSUE THREAD

**Issue by bjornlevi** [piratar/wasa2il#12]
This causes problems with user profile updates

**Comment by nifgraup** [comment]
not anymore, I get
"Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.
Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only."

**Comment by bjornlevi** [comment]
This has happened recently, without any code changes towards that part of the code. Possibly it has been covered with a django update.

Closing since there are no reproduction steps.
