### ISSUE TITLE
Allow candidates to withdraw at any time

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#120]
It would in many ways be desirable for candidates to be able to withdraw their candidacy at any time, even after voting has started. However, we need a few more things before that is safe and reasonable:
1. E-mail notifications to people who have voted for the candidate
2. A grace period so people can update their votes (so disallow withdrawl if close to the end?)
3. Double-checking the ballot counting logic to ensure this does not break anything at that end, as it will create a gap in the user's ballot sequence.

Also, @smari commented on Facebook:

> Ef kosningakerfið er ekki viðkvæmt fyrir Independence of Irrelevant Alternatives, sem Schulze er þó, þá má bara kippa frambjóðanda sem atkvæði hafa verið greidd til út áður en talið er. Annars er betra að ýmist krefjast endurkjörs eða telja með þeim frambjóðenda inni og kippa út eftir talningu.

See PR #119  for an almost-complete draft of this, which lays some groundwork but doesn't actually enable this functionality, due to the above concerns (it does other useful things though).

**Comment by BjarniRunar** [comment]
Note: check #178 for further discussion.

**Comment by BjarniRunar** [comment]
Note #190 proposes an alternative strategy that may remove the need for withdrawls (and recounts) almost entirely.

**Comment by helgihg** [comment]
Done. :)

https://github.com/piratar/wasa2il/commit/6e3f895d0f7bf8b751a480c6e4a2ac394d6a9603

**Comment by helgihg** [comment]
Done. :)

https://github.com/piratar/wasa2il/commit/6e3f895d0f7bf8b751a480c6e4a2ac394d6a9603
