### ISSUE TITLE
AJAX API does not use POST, has CSRF vulnerabilities

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#132]
The home-made AJAX API is riddled with CSRF vulnerabilities and does not use HTTP POST for the state-changing requests. Both urgently need to be fixed.

I have already fixed this for the election methods, in c8978b0bb331c9fa5ff2e1c38ac6bc8fb65c623b. The other parts of the app need the same treatment:
1. Place a {% csrf_token %} tag somewhere in the template (even if there is no form)
2. Use $.post() instead of $.getJSON()
3. Send the csrfmiddlewaretoken variable with the $.post()

Also it's be nice to enhance most of the AJAX methods to check whether the user has been logged out, and refresh the page if so. See 1ee8424afb024fe99c45a03bc8db4d3cd58f9bbb for the current pattern.

**Comment by 7oi** [comment]
How about just throwing out the homegrown API and replacing it with the Django REST framework? It's super easy to use and includes an awesome user interface which documents the registered API methods and how to use them

**Comment by BjarniRunar** [comment]
In my experience drastic rewrites create more bugs than they solve, both in the near and medium term. This API is still small enough that it might be an exception, although I doubt it - it took a lot of fiddling to get the voting UI to behave reasonably well, any rewrite is likely to cause regressions. It would probably still be worth doing though, just to clean things up.

But just fixing these bugs is maybe 1-2 hours of work. The fact that nobody has found the time yet for that, doesn't bode well for a larger rewriting effort. Are you volunteering? :-)

**Comment by 7oi** [comment]
I might be. To move to the Django REST framework might also be time saving in future API ventures, so investing a bit of time in moving there might be very beneficial.

I've both worked on a homegrown API and the Django REST framework and the latter is way more pleasant.

**Comment by stjanigunnars** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AJAX API does not use POST, has CSRF vulnerabilities](https://trello.com/c/C2vMb3OF/4-ajax-api-does-not-use-post-has-csrf-vulnerabilities)

**Comment by helgihg** [comment]
Fixed.
