### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Robrechtc** [piratar/wasa2il#133]
Hey folks, 

I'm a member of the Belgian Pirate Party and I think this tool would be great for organizing the party a bit more - both local crews and the national level. However, I would obviously need to change the registration - it appears that right now, it is very Icelandic-focused. I have some Python and Django experience, but I'm not quite sure what the Icekey is and how I can create a Belgian substitute. Any additional tips for using this software would be quite nice. 

Kind regards,
Robrecht

**Comment by BjarniRunar** [comment]
Hi Robrechtc! We're a bit busy right now with elections in full swing. I'll try to get back to this issue with more useful feedback once things quiet down a bit.

**Comment by Robrechtc** [comment]
Hey @BjarniRunar, thanks for the quick response! If possible, could you point me in the right direction somewhere? I've no issues with figuring it out from the docs of dependencies - of course, if the elections are too time-consuming (which I fully understand), I'll wait it out, but we're hoping to use your momentum to move PPBE forward as well, as not a lot has been happening so far. Many thanks and good luck with the elections, I know you'll do great!

**Comment by nifgraup** [comment]
@Robrechtc IceKey is a state run authentication service and is off by default in wasa2il. The text on the registration page refers to the setup for the Icelandic Pirate Party where authenticating against IceKey is mandatory.

**Comment by Robrechtc** [comment]
@nifgraup Awesome, thanks! So I just need to change the registration message then. I'll try setting up a Heroku tonight - I saw that @smari also asked for this, when it's set up I'll share it in the other issue. Thanks again!

**Comment by viktorsmari** [comment]
@Robrechtc It would be awesome if you figure out how to build this on Heroku! There is already an issue for that, nr #97

**Comment by Robrechtc** [comment]
@smari I saw :) I can't guarantee anything - if I can't get it to work I'll use a VPS - but I'd rather try getting it to work on a free service first. I'll post in #97 if it works.
