### ISSUE TITLE
Voting screen: Add how many candidates should be added/selected when voting

### ISSUE THREAD

**Issue by andri** [piratar/wasa2il#14]
Add how many candidates people have to select in an election. Right now, you can add and rearrange candidates but the UI does not tell you have many you can select.

A simple text like "x of x candidates selected" would do the trick and make more comfortable about what they are doing when voting.

**Comment by bjornlevi** [comment]
Due to the Schulze voting method no one 'has' to vote for more candidates than they want to. One is sufficient for a vote to be cast. That vote effectively means that one candidate is in first place and all other candidates are in second place (even if they are unselected)

**Comment by bjornlevi** [comment]
Also see: https://github.com/piratar/wasa2il/tree/candidate-random-order

This randomizes and persists the order of unselected candidates based on how they were loaded and how the user has ordered them. Refreshing the page gives the user a new randomized list of unselected candidates.

**Comment by BjarniRunar** [comment]
Closing as this is not necessary.
