### ISSUE TITLE
Election results - graph pop up not large enough to display column number

### ISSUE THREAD

**Issue by bjornlevi** [piratar/wasa2il#147]
![image](https://cloud.githubusercontent.com/assets/777264/17967033/9613b8dc-6ab4-11e6-91ca-6fa8a10fc786.png)

**Comment by viktorsmari** [comment]
See pull #146

**Comment by andri** [comment]
@viktorsmari came here to report this :)

**Comment by viktorsmari** [comment]
I am still waiting for admins to test / comment / merge pull #146  :)

**Comment by viktorsmari** [comment]
@7oi Close this?

**Comment by helgihg** [comment]
This has already been implemented in the code base. Closing. Thanks, @viktorsmari !
