### ISSUE TITLE
Translate _election_summary template

### ISSUE THREAD

**Issue by baldurjonsson** [piratar/wasa2il#148]
Hey there,
I was gonna take care of this myself but I fell into a deep pit of merging a Windows generated PO file with the linux one.
It's just a few strings if someone would be able to generate the new messages on a compatible box. :)

> These are the issues up for vote.
> These are the issues being discussed.
> Show all
> Show less

**Comment by viktorsmari** [comment]
You could just use a virtual box if you are in a hurry?

**Comment by PeterTheOne** [comment]
Can we make a Pullrequest out of this commit? :)

**Comment by helgihg** [comment]
This has already been fixed in the most recent version. I don't know by whom.
