### ISSUE TITLE
[User Confusion] No action to "Save" or "Submit" voting when ordering to lists

### ISSUE THREAD

**Issue by gakera** [piratar/wasa2il#16]
From a technical standpoint this is not needed, as the system automatically saves the order of candidates when a user is voting. However, from a usability standpoint this leaves the user with a feeling of "All dressed up and nowhere to go", having taken great care to order candidates in their preferred order and then ... nothing, just leave the page? 

A fix for this could be a Save button that literally does nothing, since everything is taken care of automatically. For completeness, the save button could actually save. But the experience is fixed simply by having a button that does nothing. 

Any potential confusion regarding the ability to re-order voting lists until the voting timer runs out can be addressed with a short text explaining that saving / submitting the vote can be done as many times as you want until the timer runs out.

**Comment by bjornlevi** [comment]
Just make a link that replaces the page content with "Thank you for your vote. You can submit a new vote until the vote deadline has passed here: (url to election)"

Also display the "Fara aftur í þing" button.

**Comment by BjarniRunar** [comment]
I think this is addressed by the feedback provided by the new UI code, as votes are cast. Closing until I have evidence that users are still confused. :)
