### ISSUE TITLE
UI: Show the creator of the proposal

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#161]
**Issue:**
Who is the poster of this proposal?

**Solution:**
Add his username with a link to his user profile. Maybe on the 2nd or 3rd line?

![2017-06-29_781x549](https://user-images.githubusercontent.com/1689020/27687451-2af7e012-5cd7-11e7-9d54-b9ee779003c5.png)

**Comment by bjornlevi** [comment]
Problem is that it's usually an admin that adds the proposal, which is not
the original author (usually)

**Comment by 7oi** [comment]
So, do you have to be an admin to create proposals (still trying to wrap my head around everything)? Even so, adding a field to change proposals for author (possibly a manytomany field for multiple authors) would not be such a bad idea, especially if the proposals are frequently created by admins.

That being said, why are admins always creating the proposals, not the authors?

**Comment by PeterTheOne** [comment]
In LiquidFeedback an author can invite more authors, they can accept the invitation, then they will be shown and also have the right to edit the proposal.

**Comment by bjornlevi** [comment]
Well, polity moderators can add proposals and elections. It used to be
everybody but the results of that were confusing...

Being able to pick an author might be the option but then the author might
not be registered (it's  not a requirement)

**Comment by 7oi** [comment]
@PeterTheOne I like that. That could be something to think about, although the implementation would be a bit (meaning a lot) more work.

@bjornlevi Well, the authors field could of course just be null if the author is not registered. Or it could even just be a simple text field for that matter with a comma separated list of authors. Doesn't really need to link to users...

I like how a simple issue that would just require a template change turned into something "slightly" more.

**Comment by helgihg** [comment]
We can show the username of the corresponding documentcontent, which is the person who made the actual content, not the person who initiated the vote. I don't know why we would show who initiated the vote, seeing that's usually just some system administrator or officer of the polity.

Would that suffice in your opinions, @viktorsmari and @bjornlevi ?

**Comment by helgihg** [comment]
We can show the username of the corresponding document content, which is the user who made the actual content, not the person who initiated the vote. I don't know why we would want to show who initiated the vote, seeing that's usually just some system administrator or officer of the polity.

Would that suffice in your opinions, @viktorsmari and @bjornlevi ?

**Comment by helgihg** [comment]
Implemented: commit 746907c
