### ISSUE TITLE
WYSIWYG markdown editor

### ISSUE THREAD

**Issue by 7oi** [piratar/wasa2il#165]
## ...because not everyone knows how to use markdown.

There are many solutions out there. I myself have implemented **CKEditor** in a django site before and **CKEditor** has a markdown plugin as well.

I think that would just be more friendly to see a familiar text editing field. We geeks don't mind the markdown, but we have to think of the muggles. We want them to be able to do it all without requiring assistance, right?

**Comment by helgihg** [comment]
I agree, but I also have another idea, just to think about. Perhaps it were best if the users were not concerning themselves with layout at all. Maybe they should just enter sentences which then get automatically formatted according to specific rules. This would mean a separate field for each reason (under "Considering bla bla bla...") and each point in the policy itself.

It requires a lot of more work and would be difficult if not impossible to do for many of the existing policies, but if this is how it worked, it would completely end all the work we have to put into making the policy displays consistent and appealing.

**Comment by 7oi** [comment]
Indeed, that solution would improve consistency and such, but I have actually implemented such a thing. It was not pretty. It resulted in a ever growing form as you could add as many elements as you wanted. Posting said form could then be problematic and needed server adjustments as it was way larger than forms are supposed to be.

I have a feeling that if we just have a WYSIWYG editor with a styleguide available (could be accessible with the press of a button, perhaps?) would probably be sufficient, not to mention backwards compatible with all current markdown formatted data. Most people know how to use word processors and these WYSIWYG editors are great at mocking those. We can also disable/enable available toolbar options in them at will, so users pretty much have no option but to follow the styleguide. 😜

**Comment by helgihg** [comment]
Found this while browsing for solutions to a different problem in a different project:: http://hallojs.org/demo/markdown/

It seems really, really simple, and it's published under the MIT license.

**Comment by stjanigunnars** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WYSIWYG markdown editor](https://trello.com/c/vEz8U4xO/8-wysiwyg-markdown-editor)

**Comment by smari** [comment]
Þetta er mikið til komið, eins og sjá má í stillingum fyrir notanda, en það vantar að setja viðeigandi formfield á stefnuritun og annað álíka þar sem það á við.

**Comment by HermannBjorgvin** [comment]
Lítur vel út þessi nýji. +1

**Comment by smari** [comment]
This is basically done on my end and will be available shortly.
