### ISSUE TITLE
[User Confusion] A more obvous "You need to be logged in to vote" prompt would be helpful

### ISSUE THREAD

**Issue by gakera** [piratar/wasa2il#17]
When on a voting page, there needs to be a clearer indication that a user needs to be logged in to vote, especially on mobile.

Since the system automatically logs out users after a certain time, but then is not very obvious about it, user confusion can arise from the interface not offering the voting option. For example, I thought I was logged in and that the voting had not been started because the meeting was running late (aðalfundur), a classic disconnect between my mental model and the actual system logic. 

A fix could be two fold: 
1) A more obvious prompt when a user is logged out due to inactivity (Igloo software does this nicely, with a "session expired" overlay over the whole page, and a countdown timer that the user can cancel before the actual logout happens). 
2) A more prominent "You need to be logged in to vote" call to action on the voting pages.

**Comment by BjarniRunar** [comment]
Fixed!

**Comment by BjarniRunar** [comment]
Actually, no this isn't fixed. Only 2) is fixed. Reopening.

**Comment by BjarniRunar** [comment]
Relates to #95.

**Comment by helgihg** [comment]
Implemented in commit b8b37c6.
