### ISSUE TITLE
Help-page with the the pros and cons of internet-voting

### ISSUE THREAD

**Issue by helgihg** [piratar/wasa2il#171]
Internet voting (still) has its fundamental pros and cons which users should be aware of before casting their votes.

**Comment by smari** [comment]
Instead of a dialog, simply put a button on any page where voting can occur leading to a help page. Simpler and probably better.

**Comment by helgihg** [comment]
Agreed. Title updated accordingly.

**Comment by helgihg** [comment]
This has been implemented via terms-and-condition in commit https://github.com/piratar/wasa2il/commit/2eb6d7a5a2cde20a9f9e24d02663aa207d27cee9. The instance's administrator is responsible for writing a EULA or terms-and-conditions that elaborate on how data is managed.
