### ISSUE TITLE
Laga texta í pósti sem sendur er til staðfestingar á netfangi.

### ISSUE THREAD

**Issue by stjanigunnars** [piratar/wasa2il#176]
![image](https://user-images.githubusercontent.com/7986105/29826407-badaa682-8cc6-11e7-9666-7bf6329fa14f.png)

Nýr texti fyrir tölvupóst:

Til að virkja aðgang þinn þarf að staðfesta netfang með þvi að smella á helkkinn hér að neðan.
x.piratar.is/accounts/activate/96615daae1cfa2623e3523cb505bb6d211659f7a/

Þetta er staðfesting á skráningu á x.piratar.is. Ef þú varst ekki að skrá þig þá vinsamlegast líta framhjá þessum pósti og skráning þín verður fjarlægð skjálfvirk. 

Við þökkum kærlega fyrir stuðninginn og þátttökuna. 

Píratar

**Comment by helgihg** [comment]
Text version also updated accordingly.
