### ISSUE TITLE
Where is this information updated?

### ISSUE THREAD

**Issue by stjanigunnars** [piratar/wasa2il#177]
![image](https://user-images.githubusercontent.com/7986105/29826691-79c732ea-8cc7-11e7-8cff-ca2129fbb55f.png)

**Comment by helgihg** [comment]
Are you referring to the text displayed? It's in an HTML file which then gets translated via GetText, meaning it's not configurable presently. If you want different text in there, I can update the files, it's no problem.

**Comment by helgihg** [comment]
Closing due to ambiguity, having conversed with @stjanigunnars .
