### ISSUE TITLE
Ability to limit the number of candidates that are shown at the end of election

### ISSUE THREAD

**Issue by helgihg** [piratar/wasa2il#183]
Sometimes, especially when using Schulze, there is a desire to only show a certain amount of the top candidates, without the bottom. The point is to avoid unnecessarily pointing out those who were the most unpopular.

**Comment by BjarniRunar** [comment]
There is currently a setting, to control the statistics. I take it that setting is JUST for the statistics, not for the final list displayed?

It does seem it would make sense to use the same number for both, the rationale for having the number at all is largely the same.

**Comment by helgihg** [comment]
Resolved with commit 7be26e58cd553d9cc66871641fc3043aa64e224a.
