### ISSUE TITLE
Provide election admins with more useful data

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#189]
After an election (and maybe during), admins should be able to download a structured document (CSV, ODS, JSON, ...) that tells them all they need to know about the election and the candidates.

The system knows peoples' names, e-mails, and in the Icelandic case, kennitala - all of which is information the people managing the elections actually need to have. Today election admins need to take extra steps to capture this information, often resulting in a duplication of effort and confusion amongst candidates. We should make wasa2il expose this information in a reasonable format to the admins.

If there are privacy concerns, then we could address them by requiring consent from users before they can add their names to a ballot.

**Comment by helgihg** [comment]
Implemented in commit f71e5bb.
