### ISSUE TITLE
Remove field polity.is_nonmembers_readable

### ISSUE THREAD

**Issue by helgihg** [piratar/wasa2il#191]
This field was originally intended to provide some sort of privacy for polities. It is neither capable of achieving that goal without massive revision of other parts of the project, nor is it currently being used.

Seeing that it's pointless at best, deceptive at worst, I recommend we remove this feature-wannabe.

I'd like opinions, though.

@BjarniRunar @bjornlevi @stjanigunnars @smari

**Comment by BjarniRunar** [comment]
Agree. If it's not being used, removing it reduces confusion in the code-base: "What is this? Why doesn't it work? wtf?"

If/when people implement do implement private polities, then re-adding the setting at the same time is a pretty minor thing compared to the rest of the work involved.

**Comment by helgihg** [comment]
Done. Commit c14b2cd.
