### ISSUE TITLE
UX: When switching between your 'Þing' it should not appear at the bottom

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#203]
When you are at any page which has "Þing" in the breadcrumb, and click it, because want to switch between Þings, they are shown at the bottom, almost offscreen on a 1920x1080 screen!

**Solutions:**
Show it at the top?
Have a special page only for Þings?

![2018-03-09_789x1027](https://user-images.githubusercontent.com/1689020/37205497-45c65f88-2395-11e8-830a-bbcc0034643a.png)

**Comment by baldurjonsson** [comment]
I intended this summary page to be the new "frontpage". If you have no "front polity" it will show at the root of the app.
It was put on this page as well as a quickfix

Suggestion: Disable the Front policy and remove this from /polities 
Pull request for reference: https://github.com/piratar/wasa2il/pull/138

**Comment by helgihg** [comment]
Note that a major overhaul of the UI is underway.

**Comment by helgihg** [comment]
The navigation has been completely redesigned. I'm closing this issue since the problems it describes are no longer there. :)
