### ISSUE TITLE
Commonmark package update breaks `master` and `development` branch

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#214]
On the newest `master` and `development` using `virtualenv` the change from
CommonMark 0.7.5 to
commonmark-0.8.1
in requirements.txt
breaks the application with error:
```
InvalidTemplateLibrary at /
Invalid template library specified. ImportError raised when trying to load 'prosemirror.templatetags.prosemirror': No module named CommonMark.blocks
```
Reverting the package solves the issue.

How can we stop these basic errors from going into the `master` branch? 
Don't we have any tests on Travis that can forbid merging these PRs into a branch?

**Comment by viktorsmari** [comment]
Travis tried to warn us with a red :x: :laughing: 
![2018-10-21_16-32-18](https://user-images.githubusercontent.com/1689020/47268260-f3d83b80-d54e-11e8-8f72-f3413e608d79.png)

**Comment by helgihg** [comment]
Travis was set put in place by a previous developer, and I was unable to
figure out what went wrong, and since no one was around to maintain the
Travis testing thing, I disabled it.

**Comment by viktorsmari** [comment]
@helgihg I volunteer to maintain mr Travis!

**Comment by viktorsmari** [comment]
@helgihg Travis has been fixed. The API key ran out, it needs to be renewed yearly.
However, we still have errors on the app itself on https://wasa2il-development.herokuapp.com/
We need to look at #212 which will also close #216
