### ISSUE TITLE
Mobile nav menu: Where is log out / log in button? + BUG

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#217]
I found **3 issues** on mobile Nav menu

 

- [X] ~~When on mobile, how do you know if you are logged in or not~~ 
     * Should we add info on the Nav menu if you are?
- [ ]  BUG: Click ANY link at the black bottom (**About wasa2il** - Notandaleyfi - etc.)
     * Click the hamburger menu. It is now empty!
- [ ]  With the nav menu open, you **should be able** to click OUTSIDE it to close it.
     * You should not be forced to click a link in order to close it.
     * This is expected behaviour on most menus.

![2018-12-07_10-28-48](https://user-images.githubusercontent.com/1689020/49639318-f31a3c80-fa0a-11e8-81f2-781f9cea471c.png)
![2018-12-07_10-31-37](https://user-images.githubusercontent.com/1689020/49639438-4b513e80-fa0b-11e8-8c4e-178c74e62b16.png)

**Comment by smari** [comment]
This is fixed. 
![image](https://user-images.githubusercontent.com/180166/49688637-188f6f00-fb0d-11e8-9ad2-e4d1d336c671.png)

![image](https://user-images.githubusercontent.com/180166/49688671-5a201a00-fb0d-11e8-98a7-8e1f81765f2b.png)
