### ISSUE TITLE
Improve installation instruction for beginners

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#25]
When trying to following debian instruction I get multiple errors, first one after issuing

`pip install -r wasa2il/requirements.txt`
*Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s35t9oe9/suds*

I fixed that by doing `sudo pip2 install -r wasa2il/requirements.txt` but I have no idea if that is a good solution.

Then when I run the server and visit localhost:8000 I get:
*ImportError at /
No module named context_processors*

Environment: Ubuntu 15.10

**Comment by bjornlevi** [comment]
You have probably forgotten to activate the virtual environment, "source ..."

**Comment by gakera** [comment]
Ég er búinn að reyna að keyra í gegnum þessar leiðbeiningar milljón sinnum, aðallega til að fá Docker til að virka en líka bara til að prófa. Hefur ekkert gengið.

**Comment by bjornlevi** [comment]
bæði linux og windows install dótið virkar mjög vel hjá mér. Makki?

**Comment by gakera** [comment]
Ég var að reyna að setja þetta upp inní docker container, fyrst python image (sem er Debian) og svo ubuntu, hvorugt virkar. Hvorki á makka né windows hérna í vinnunni. Kom alltaf þessi villa sem ég talaði um á slack.

**Comment by viktorsmari** [comment]
Ég var einmitt að reyna að installa docker, virkaði ekki.
Setti upp nýtt Ubuntu 12.04 í virtual, virkaði ekki.

**Comment by bjornlevi** [comment]
Hef verið að nota ubuntu 14.x
Villan að ofan er líklega django villa.

**Comment by viktorsmari** [comment]
Það væri frábært ef reynslumeiri menn gætu gert ítarlegri leiðbeiningar svo að nýgræðingar geti tekið þátt í þessu :)

**Comment by gakera** [comment]
Það sem ég fæ er Django villa held ég líka, ImportError: cannot import name RequestSite við migrate dæmið.

**Comment by gakera** [comment]
og þúst bara svona ps, hvert einasta comment endar sem message inní slack spjallinu okkar :P
