### ISSUE TITLE
Installation does not work - please improve setup instructions if something is missing.

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#32]
After doing ` ./inital_setup.py` I get the error:

Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-MDpzaV/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PL0mJS-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-MDpzaV/pillow
Storing debug log for failure in /tmp/tmpLZ5NTi
Dependency installation seems to have failed. Continue anyway? (yes/no): 

Environment:
Ubuntu 15.10
pip 1.5.6
python 2.7
django-admin 1.7.9

**Comment by helgihg** [comment]
That error doesn't really contain an awful lot of information.

Can you give us roughly the last 20-30 lines of /tmp/tmpLZ5NTi (or
whatever else where it says it stores the debug log for failure)?

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by viktorsmari** [comment]
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-MDpzaV/pillow/setup.py", line 767, in <module>

    zip_safe=not debug_build(),

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run

    self.run_command('build')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run

    self.build_extensions()

  File "/tmp/pip-build-MDpzaV/pillow/setup.py", line 516, in build_extensions

    (f, f))

**ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting**

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-MDpzaV/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PL0mJS-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-MDpzaV/pillow
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 309, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-MDpzaV/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PL0mJS-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-MDpzaV/pillow

**Comment by helgihg** [comment]
If you're using a Debian-based system, try installing the Debian package
libjpeg8-dev. If you're on a different kind of system, try to find the
corresponding package to the same library.

(A lot of OSes are Debian-based these days.)

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by viktorsmari** [comment]
After installing libjpeg8-dev, I was able to run the project `python manage.py runserver` but when I visit the page I get the following:

ImportError at /
No module named context_processors
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.7.9
Exception Type:	ImportError


I think we should wait with this issue for now, I was able to build the project on my home machine which almost the same environment setup, Ubuntu (Studio) 15.10.

**Comment by helgihg** [comment]
It could be the Django version. The one specified in requirements.txt is
Django version 1.8.7, but you're using version 1.7.9.

(One of my grudges with Django is that they keep doing
backward-incompatible changes every few months.)

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by viktorsmari** [comment]
Same issue confirmed, now on a virtual machine running Ubuntu 14.04, django 1.8.7 

`ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting`

It would be nice to get better setup instruction with more detailed software versions and OS recommendation.

For example "we recommend this virtual image/ this OS, django x.x.x, django-admin"

All the process installing django, required software and running the inital_setup could be around 5 lines?

**Comment by viktorsmari** [comment]
Now I tried installing on Ubuntu 16.04 with python 2.7.11+

To begin I had to install the following:
 * `python-pip` from repo, pip version 8.1.1
 * `libmysqlclient-dev`
 * `libjpeg8-dev`

And then it fails on:

```
Collecting suds==0.4 (from -r requirements.txt (line 27))
Collecting setuptools>=11.3 (from cryptography==1.3.1->-r requirements.txt (line 4))
  Using cached setuptools-21.2.1-py2.py3-none-any.whl
Installing collected packages: pytz, Babel, certifi, pycparser, cffi, setuptools, ipaddress, six, pyasn1, enum34, idna, cryptography, defusedxml, diff-match-patch, Django, django-bootstrap-form, django-registration-redux, future, eight, ipython, lxml, markdown2, MySQL-python, Pillow, PyMySQL, pyOpenSSL, signxml, suds
Dependency installation seems to have failed. Continue anyway? (yes/no): yes
Checking if Django is installed... yes (1.8.10)
Checking local settings configuration:
- No changes needed.
['pybabel', 'compile', '-d', '/home/viktor/wasa2il/wasa2il/locale', '-D', 'django', '-l', 'fr']
Traceback (most recent call last):
  File "./initial_setup.py", line 140, in <module>
    subprocess.call([get_executable_path('pybabel'), 'compile', '-d', os.path.join(os.getcwd(), 'wasa2il/locale'), '-D', 'django', '-l', lang])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by BjarniRunar** [comment]
I had little difficulty following instructions and getting things up and running; I agree this can be closed and am going to exercise my new SuperPowers and do just that. :)
