### ISSUE TITLE
Create "Dummy data" so we can load via "manage.py loaddata" command

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#39]
This would be a "nice to have" for developers who don't want to go through the process of creating their own data when working on a small feature.

**Comment by viktorsmari** [comment]
So if someone has some fine "dummy data" in the database (some documents, issues, elections and so on) and is willing to share:
`python manage.py dumpdata dump.json`
After that, others can use that file (if they want to) via
`python manage.py loaddata dump.json`

**Comment by bjornlevi** [comment]
I'll commit tomorrow

**Comment by bjornlevi** [comment]
https://github.com/piratar/wasa2il/commit/2935285bed74e6d1b8df2060cd0516a0ced954d0

default superuser pirate:pirate
users u1:asdf & u2:asdf
