### ISSUE TITLE
Voting without joining the party

### ISSUE THREAD

**Issue by busla** [piratar/wasa2il#42]
Seems that I can register on x.piratar.is and vote without joining the party. Or do I automatically join the party when I sign up?

If so, then I don´t remember getting an "Agree to terms" option when I signed up.

**Comment by bjornlevi** [comment]
You automatically join:
https://x.piratar.is/accounts/register/
"Vinsamlegast athugið að með því að nýskrá og staðfesta aðgang gerist þú meðlimur að Pírötum."

**Comment by busla** [comment]
:+1: the first sentence.

Says something about my lack of attention to signup agreements.
