### ISSUE TITLE
limited number of characters for usernames

### ISSUE THREAD

**Issue by bjornlevi** [piratar/wasa2il#44]
Not checked during registration, leading to users with long usernames getting truncated names and unable to guess and login.

**Comment by stjanigunnars** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [limited number of characters for usernames](https://trello.com/c/RzoIrZb1/7-limited-number-of-characters-for-usernames)

**Comment by helgihg** [comment]
This appears to have been fixed in more recent versions of Django. Closing.
