### ISSUE TITLE
UI: Enduröðun - færa "Ný mál" efst

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#47]
Þetta er mögulega persónubundið en ég skoða einungis "Ný mál" í snjallsímanum og sá flokkur er neðst.

Væri til í að hafa eina hlutinn sem ég nota efst, en ekki neðst. 

Hvað segið þið?

Eins væri hægt að færa "Kosningar" næst efst svo það væri meira áberandi en ég veit ekki hversu oft sá dálkur er notaður.

**Comment by helgihg** [comment]
Ég er sammála. Ég hef ætlað að fara aðeins yfir útlitið á forsíðunni í
dágóðan tíma. Björn Leví gerði einhvern tíma tilraun, en hún virkaði
illa með hinum þingunum og allt fór í steik þar, þ.e.a.s. í undirþingum
á borð við Pírötum í Reykjavík og slíku.

Annað sem ég var að pæla, var að hafa það hluta af einhverri aðeins
meiri heildaruppfærslu, þá líka á því hvernig málin eru sýnd (þ.e.
atkvæðagreiðslur) og skjöl og svoleiðis. Mér þætti gaman að taka nokkra
hluti í einu, ekki bara forsíðuna, aðallega því að þá upplifi notendur
að eitthvað heilsteypt hafi verið gert. Ef útlitinu er breytt smátt og
smátt á mismunandi stöðum hef ég áhyggjur af því að upplifun notenda
verði frekar á þá leið að það sé sífellt verið að rugla hann í ríminu.

Hvað finnst þér?

Með kveðju,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by viktorsmari** [comment]
Ég sem notandi er bæði vanur því að fá margar smáar uppfærslur og eina stóra en mér er alveg sama hvora leiðina við förum, fer auðvitað eftir útfærslunni og hvort þetta sé ruglandi eða ekki.
Ég þekki kerfið ekki nógu vel til að meta hvað hentar því betur.

En já, hvar ættum við að safna þessum punktum saman?  
Eigum við að búa til issue fyrir hvert atriði sem okkur langar að sjá?

Það var t.d. annað atriði sem ég væri til í að sjá, að geta séð lykiltölur eins og þátttöku í Samþykktum án þess að þurfa að fara inní Skjalið og þurfa að smella á "Tilheyrandi mál".
Þannig að beint á forsíðunni væri hægt að sjá eitthvað svona:

![2016-02-01_564x203](https://cloud.githubusercontent.com/assets/1689020/12728911/5a486348-c924-11e5-89a0-ffcf37d51b42.png)

**Comment by helgihg** [comment]
Spurning hvort við getum safnað í einhvern lista hlutum sem við myndum
vilja bæta við í einum rykk. Kannski væri gott að hafa lista yfir
kannski 8-10 atriði sem við tökum síðan saman í einu.

Það er líka hægt að fara einhverja millileið. Heldur stórar, en ekki of
tíðar breytingar, samt fleiri en ein stóra. Það gæti líka jafnvel
hjálpað okkur að mynda okkur einhverja heildarsýn.

Annað sem þyrfti að bæta við er að breyta þessu úr lista yfir í tré:
https://x.piratar.is/polities/

Og sömuleiðis í spjaldinu sem kemur upp þegar maður smellir á "7
undirþing" á forsíðunni.

Eigum við að safna í 8-10 liða issue í einu? Hvernig hljómar það?

**Comment by viktorsmari** [comment]
Hljómar mjög vel!
