### ISSUE TITLE
UI: "In voting" under "New issues" should stand out more

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#48]
![2016-02-01_407x224](https://cloud.githubusercontent.com/assets/1689020/12726711/57cd2e24-c919-11e5-8846-cd1491237e22.png)

Suggesting to make this bold, or change text color or background so it catches more attention

**Comment by helgihg** [comment]
Implemented in commit 8ee45bc. (Simply made <strong>.)
