### ISSUE TITLE
process issues and documents inside the system

### ISSUE THREAD

**Issue by bjornlevi** [piratar/wasa2il#56]
Currenly there is a crontab job that "checks" for expired issues and sets the status of documents and issues accordingly. This should be done within the view method for the document and issue - if not processed and expired: process and file according to vote results.

**Comment by bjornlevi** [comment]
missing: process predecessors to expired status

**Comment by BjarniRunar** [comment]
Strongly disagree. There's nothing wrong with cron jobs, they are very often the right tool for the job. If you'd like me to give you a crash course in how to use them, I'm happy to help!

On the other hand, doing things on-the-fly in views is a nasty antipattern which can lead to race conditions, shitty performance and all sorts of other badness. As a general rule of thumb, viewing data should not have the side-effect of changing data.

I don't understand your second comment, if you're reporting a bug you need to clarify it a bit. :)

**Comment by helgihg** [comment]
I agree with @BjarniRunar. In light of discourse, I'm closing this issue. Good talk, though.
