### ISSUE TITLE
Unable to loaddata, can someone perform 'dumpdata  --natural-foreign' ?

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#67]
Maybe after a django update I am unable to perform `loaddata`.

I am also unable (or don't know how) to vote in my local system.

I would appreciate someone (maybe @bjornlevi ?)  to perform a new 

`manage.py dumpdata --natural-foreign > wasa2il/default_data/mydump.json`

and commit it. Especially if they have some voting statistics available.

**Comment by bjornlevi** [comment]
Most likely some model update, I'll update the example data dump.

**Comment by viktorsmari** [comment]
Can you notify me when this is done? I need this for a feature I am working on.

**Comment by BjarniRunar** [comment]
I don't have any shareable test data yet, if @bjornlevi could share his that would be helpful for now. 

Longer term, I think we should have a python script that generates test data, so we can be sure it stays in sync with the active model. I'll create an issue for that.

**Comment by viktorsmari** [comment]
I think this issue can be closed.
