### ISSUE TITLE
UI: Should we allow users to indicate what they vote?

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#68]
A lot of users tell other users what they'll  vote in the comments to persuade others to do the same.

Should we make this a feature, allowing users to display how they cast their vote?
It could be visible on every comment they make with either a font-awesome icon or a colored box of some sort.

 Here is a bad graphical example:

![2016-05-29_561x62](https://cloud.githubusercontent.com/assets/1689020/15632979/bd430406-25a1-11e6-9ff1-d7e8203101f7.png)

It could f.x. be implemented as a checkbox in the voting section.

**Comment by bjornlevi** [comment]
Það var áður þannig að staða atkvæða sást. Það er hins vegar mögulega
skoðanamyndandi og getur haft ruðningsáhrif á niðurstöðu kosninganna. Fólk
verður allavega að þurfa að hafa fyrir því að lesa rökstuðninginn í staðinn
fyrir að þurfa bara að skanna rauð og græn merki (imo)

**Comment by viktorsmari** [comment]
Mjög góður punktur.

**Comment by helgihg** [comment]
Ég held þú sért að tala um tvennt ólíkt.

Það var þannig að maður sá, á meðan á atkvæðagreiðslu stóð, hversu mörg
já-atkvæði og hversu mörg nei-atkvæði hefðu verið greidd. Það er
skoðanamyndandi og fínt að hafa það falið.

Hitt er síðan hvort að notandi eigi að geta flett upp sínum fyrri
atkvæðagreiðslum. Gallinn við það er að þá er ekki hægt að henda
atkvæðum seinna eins og hægt er að gera í kosningum um fólk (og þ.a.l.
losa sig við hin viðkvæmu kjörgögn á einhverjum tímapunkti). Á móti
kemur að það er mjög algengt að atkvæðagreiðslur um mál, þ.e. ekki fólk,
séu hreinlega opinberar. Sem dæmi er á flestum aðalfundum
atkvæðagreiðslum háttað þannig að fólk er bara með spjöld sem það lyftir
í sal smekkfullum af fólki og blaðamönnum. Þannig að þetta er ekki
næstum því jafn viðkvæmt þegar kemur að atkvæðagreiðslum um málefni
annarsvegar og þegar kemur að kosningum um fólk hinsvegar. En þá er
mikilvægt að halda til haga, að möguleikinn á leynilegum
atkvæðagreiðslum um mál þarf áfram að vera fyrir hendi, ef óskað er
eftir því.

En það er tvennt ólíkt; að gefa notandanum færi á að sjá hvernig hann
greiddi atkvæði í fortíðinni annarsvegar, og að sýna já/nei-tölurnar á
meðan á atkvæðagreiðslu stendur.

Með kveðju,
Helgi Hrafn Gunnarsson
helgi@piratar.is

**Comment by viktorsmari** [comment]
Mín pæling var sú fyrri, sem er skoðanamyndandi. Það mætti því loka þessu máli.
