### ISSUE TITLE
UI: Should we display users profile pictures next to their names in comments?

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#69]
Positive effects:
- It could encourage users to start adding their profile pictures and add more info about them selves (in user bio).
- The user base might start to know each others 'face to face'

Negative:
- It takes up a bit more space, less comments per screen, but users scroll down anyway.
- Bias? Are some more likely to follow someone with a 'nice' looking profile? :sunglasses: 

We could also implement this as a hover effect over the username but that won't work on mobile.

**Comment by bjornlevi** [comment]
I like it

**Comment by 7oi** [comment]
Implemented in #160 along with better comment section rendering
