### ISSUE TITLE
Make election page work on touch devices: add buttons

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#77]
Currently the election page's HTML and CSS has numerous bugs which make it hard or impossible to vote on phones or other small touch screens. In addition to the current drag/drop UI, we need to add explicit buttons for selecting, deselecting and reordering candidates.

This was a common complaint at the general assembly.

**Comment by PeterTheOne** [comment]
How about up and down buttons for each candidate?

**Comment by viktorsmari** [comment]
Take a look at #85 with a screenshot.

You meant something like that @PeterTheOne ?

**Comment by PeterTheOne** [comment]
@viktorsmari looks good :+1:

**Comment by BjarniRunar** [comment]
This is great! There's one outstanding issue I found.

To reproduce:

1) vote for someone, pressing the vote button
2) undo that, removing them by pressing the red X

Result:

Candidate is correctly moved back to right-hand column, but has no vote button. The only way I've found to fix is to refresh the page.

Expected result:

Candidate should have vote button. :-)

**Comment by viktorsmari** [comment]
I noticed this as well, this was also like this before I added my part.

So this should be a new issue I suppose, I guess the culprit is somewhere around line 13 in

wasa2il/templates/core/_election_candidate_list.html

`
if candidate_selected
`

**Comment by BjarniRunar** [comment]
This will be closed by my latest PR, so don't go working on it. :-)
