### ISSUE TITLE
Fix election page CSS, so vote buttons don't move around

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#78]
There are bugs in the election page at the moment, which allow the voting buttons to move around. 

This can be triggered by creating a candidate with a very long name, but other conditions may also cause problems. This is very bad, as it causes the button for one candidate to move to another, potentially causing voters to cast incorrect votes if they're not paying attention to the selected list (which is harder to do on small screens anyway).

This issue was observed at the general assembly.

**Comment by BjarniRunar** [comment]
I also saw election pages where some candidates were lacking a vote button entirely. This may have been the same root cause.

**Comment by BjarniRunar** [comment]
Also see #77 - it's likely that these two issues could be addressed together.

**Comment by viktorsmari** [comment]
I am willing to work on this as soon as I get some test data that includes some elections.
I am unable to create them on my local machine (don't know how).

So if someone would create a nice test / dummy data (which closes #67) , that would be great! :dancers:

**Comment by BjarniRunar** [comment]
This may have been fixed by #85 , will verify and close if so. :)

**Comment by BjarniRunar** [comment]
This looks fixed to me. Closing until someone reports otherwise - thanks @viktorsmari, awesome work!
