### ISSUE TITLE
Preserve anonymized election ballots, allow downloads

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#80]
In some elections, we want to allow people to download raw ballot data and re-count themselves.

I have a PR in flight #74, which writes such data to a static JSON file before deleting, but it would probably be better to write the data to a custom table in the database itself and create a JSON / CSV / ... download view.

**Comment by BjarniRunar** [comment]
Progress was made in 2cb5382d57cfae57a74bf4fdf42ee3d98042e3b5.

**Comment by BjarniRunar** [comment]
Notes: The main argument against publishing raw ballot data, is that it may "break" anonymity if a user's ballot is unique.

The publishing system should be able to evaluate this on its own and either publish a safe subset of the data, or decline to publish if anonymity cannot be preserved.

1) Anonymity can be improved by truncating ballots as much as possible (code for this exists)
2) After truncating, if any ballots are still unique, we could decline to publish or we could omit those ballots and if they leave the results unchanged, publish the rest.

Both 1) and 2) do involve publishing "cooked" data, instead of publishing the raw original ballots, but I don't think publishing raw data is compatible with anonymity anyway.

**Comment by BjarniRunar** [comment]
Update: The truncating ballots experiment has been abandoned. After doing some math, it became apparent that the number of cases where this actually results in a truly anonymous set of ballots is miniscule; the vast majority of the time this would be a complete waste of time.

This effectively is now a policy decision; users of wasa2il need to decide which they value more:

1. Anonymity of voters: in particular the guarantee that voter cannot prove to a third party after the election how he or she voted.
2. Auditability of the voting process: when ballots are published users can check to ensure their ballot is present in the full data-set, and they can perform their own re-count.

If 1. is given priority, then publishing ballot data must be avoided. This alone is not sufficient to prevent coercion or bribery, but it does eliminate the most convenient way of doing that (other methods involve borrowing user credentials or physical oversight as they vote, and are mitigated somewhat by the fact that users can modify their ballots at any time, and wasa2il admins could monitor server logs for abnormal use patterns).

If 2. is given priority, then publishing ballot data may be helpful. However it should be noted that a sneaky admin can affect the elections in many other ways, in particular by creating fake users or by looking for identical ballots and replacing only some of them.

**Comment by PeterTheOne** [comment]
Btw. LiquidFeedback doesn't have anonymous voting, all ballots are published to the user base (with pseudonyms that users can choose). Arguing that the software/hosting/admin cannot be trusted.

**Comment by BjarniRunar** [comment]
@PeterTheOne, as discussed above, the admin is not the only potential adversary. In fact, if your admin is your primary adversary then you probably have bigger problems than can be solved with code. I don't know if Liquid Feedback even attempts to prevent bribery or coercion.

In some use cases that sort of thing isn't really a concern, but when you're starting to talk about parliamentary elections it probably should be, and we do plan to use wasa2il for our primaries, selecting the party's potential MPs.

**Comment by BjarniRunar** [comment]
Punting this from the elections milestone - without a clear mandate from the party, after a discussion about the pros and cons of publishing, this isn't really an action item any more.

**Comment by helgihg** [comment]
I'm closing this issue, considering the discourse above.
