### ISSUE TITLE
Navigation: Put Agreements on different page?

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#89]
Agreements list will grow larger and larger.

Should we, at some point, put it on a separate page instead?

We are loading almost everything on the front page (which slows down things).

Maybe we should also put Topics on a separate page later on?

The default page could then look like this (which includes the most important things):
![2016-06-19_1325x589](https://cloud.githubusercontent.com/assets/1689020/16176761/b26bd946-3617-11e6-9e15-139cab0b7af9.png)

**Comment by bjornlevi** [comment]
I'd definitely like to put emphasis on elections (issues and people) on the
front page. But it also needs to have the "default" if, for example, there
are no elections happening.

Something like
1 2
3 4

1 is issues in voting
2 is elections in voting (missing link to election results)
3 is agreements
4 is topics

3 and 4 don't need to be full lists, they could have some random sample of
"featured" topics or agreements in a rotating window with a link to all.

**Comment by baldurjonsson** [comment]
Hi guys, long time lurker, first time commenter.
I have an idea to make a new frontpage view that includes everything "active" from all polities. Perhaps only the polities belonging to the logged in user.

This would/will come in handy when elections are held. :)

Wouldn't that solve this issue?

**Comment by bjornlevi** [comment]
Yeah, I agree.

It'd be a UI challenge though to make clearly understandable for users.

**Comment by BjarniRunar** [comment]
@baldurjonsson I think that sounds like a much needed revamp of the "my page", which I think should then become the default view for logged in users. Trying to display activity from all polities if the user isn't logged in might be useful too, but maybe a little weird that being logged in suddenly means you see *less* stuff.

There is still a need for a polity overview page which people can make sense of, in particular when they aren't logged in.

**Comment by BjarniRunar** [comment]
Related: #107

**Comment by helgihg** [comment]
This was implemented in some commit that I can't find anymore. There is now a "Show agreements" for the agreements, like there is for elections and issues.

On the performance issue mentioned above, resulting from everything being on the front page: that problem has been fixed. The page just needed some Django model query optimization..
