### ISSUE TITLE
Polity navigation is non-obvious

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#93]
In the current UI it is:

1) Not obvious how to change polities
2) Not obvious which polity you are currently looking at

Both should probably be addressed. :-)

**Comment by BjarniRunar** [comment]
... the "classic" way to address this is a crumbtrail, probably in the header.

Logo > Polities > Piratar i Reykjavik 

?

**Comment by BjarniRunar** [comment]
I suggest a crumb-trail, which both tells you where you are AND helps you navigate to other places. Alternate designs that accomplish both goals would also be fine, of course. :)

**Comment by BjarniRunar** [comment]
... also, in general, I'm a bit anal and I think that buttons are for actions, not navigation. I don't know if anyone else cares though, but I can't bring myself to saying "yes" to a navigation button. :-)

**Comment by viktorsmari** [comment]
The crumb-trail is also useful, just a question of where to place it.

**Comment by bjornlevi** [comment]
You could have a selection menu next to the logo showing the active polity.
LOGO piratar >

Click the polity and select "Píratar í Reykavík" results in
LOGO Píratar í Reykjavík >

**Comment by baldurjonsson** [comment]
Is this anything you guys would be interested on a pull request on?

![image](https://cloud.githubusercontent.com/assets/3398226/17494416/158968b4-5da4-11e6-9869-eb1205665aa9.png)

Basicly a breadcrumb added to the template, could be added to the context in views as well

> 
{% block breadcrumbs %}
{% add_breadcrumb _('Polities') '/polities' %}
{% add_breadcrumb polity.name %}
{{ block.super }}
{% endblock %}

**Comment by baldurjonsson** [comment]
To give a better view of the idea, here's a long breadcrumb

![image](https://cloud.githubusercontent.com/assets/3398226/17497195/2e6ca98e-5db0-11e6-89b3-aa8303e2bd7e.png)

**Comment by helgihg** [comment]
Hopefully fixed in commit 716dbe1. Probably more changes will be made when experience is gained with this new way of navigating.
